/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interficius;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pedidos.Pedidos;

/**
 *
 * @author ALUMNOS_FP
 */
public class Interficius extends javax.swing.JFrame {

    /**
     * Creates new form Interficius
     */
    public Interficius() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        jOptionPane1 = new javax.swing.JOptionPane();
        ConPatatas = new java.awt.Checkbox();
        Comprar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        Mesa = new javax.swing.JLabel();
        jTextFieldMesa = new javax.swing.JTextField();
        Pollo = new javax.swing.JRadioButton();
        Mixto = new javax.swing.JRadioButton();
        Ternera = new javax.swing.JRadioButton();
        listaComida = new javax.swing.JComboBox<>();
        conBebida = new javax.swing.JCheckBox();
        conPatatas = new javax.swing.JCheckBox();
        conSalsa = new javax.swing.JCheckBox();
        conVerdura = new javax.swing.JCheckBox();
        verPedidos = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        ConPatatas.setLabel("Con Patatas");
        ConPatatas.setName("ConPatatas"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        Mesa.setText("Mesa");

        jTextFieldMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Pollo);
        Pollo.setText("Pollo");
        Pollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolloActionPerformed(evt);
            }
        });

        buttonGroup1.add(Mixto);
        Mixto.setSelected(true);
        Mixto.setText("Mixto");
        Mixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixtoActionPerformed(evt);
            }
        });

        buttonGroup1.add(Ternera);
        Ternera.setText("Ternera");
        Ternera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerneraActionPerformed(evt);
            }
        });

        listaComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kebab", "Durum", "Lahmacun", "Plato", " " }));
        listaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaComidaActionPerformed(evt);
            }
        });

        conBebida.setText("Con Bebida");

        conPatatas.setText("Con Patatas");

        conSalsa.setText("Con Salsa");

        conVerdura.setText("Con Verdura");

        verPedidos.setText("Mostrar Pedidos");
        verPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mixto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ternera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pollo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conBebida)
                        .addGap(6, 6, 6))
                    .addComponent(conPatatas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conSalsa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conVerdura, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Comprar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listaComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mesa)
                    .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Pollo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ternera)
                        .addGap(18, 18, 18)
                        .addComponent(Mixto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(conBebida)
                        .addGap(18, 18, 18)
                        .addComponent(conPatatas)
                        .addGap(18, 18, 18)
                        .addComponent(conSalsa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conVerdura)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPedidos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Comprar)
                        .addComponent(jButton2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<Pedidos> pedido = new ArrayList<>();
    int nPedido = 1;
    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        nPedido++;
        int nMesa = Integer.parseInt(jTextFieldMesa.getText());
        String nomCama = jTextFieldNombre.getText();
        Double precioPedido = 3.5;

        //Calcular PRECIO
        //Opciones RadioButton
        if (Ternera.isSelected()) {
            precioPedido += 1;
        } else if (Mixto.isSelected()) {
            precioPedido += 1.5;

        }
        //Opciones de la checkbox
        if (conBebida.isSelected()) {
            precioPedido += 1;
        }
        if (conPatatas.isSelected()) {
            precioPedido += 0.5;
        }
        if (conSalsa.isSelected()) {
            precioPedido += 0.25;
        }
        if (conVerdura.isSelected()) {
            precioPedido += 1;
        }
        String comboSelecionado = listaComida.getSelectedItem().toString();

        if (comboSelecionado.equals("Durum")) {
            precioPedido += 1;
        } else if (comboSelecionado.equals("Kebab")) {
            precioPedido += 0.5;
        } else if (comboSelecionado.equals("Lahmacun")) {
            precioPedido += 1;
        }

        Pedidos newPedido = new Pedidos(precioPedido, nPedido, Integer.parseInt(jTextFieldMesa.getText()), jTextFieldNombre.getText());
        pedido.add(newPedido);
        JOptionPane.showMessageDialog(rootPane, "Has vendido tu alma " + "Has selecionado " + newPedido.toString());

    }//GEN-LAST:event_ComprarActionPerformed

    private void PolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PolloActionPerformed

    private void MixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MixtoActionPerformed

    private void TerneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerneraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerneraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "No has vendido tu alma");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void listaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaComidaActionPerformed

    private void verPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPedidosActionPerformed
        String msg="";
        for (Pedidos ped : pedido){
          msg += ped+"\n";  
        }
            
        JOptionPane.showMessageDialog (rootPane, msg);
    }//GEN-LAST:event_verPedidosActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interficius().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprar;
    private java.awt.Checkbox ConPatatas;
    private javax.swing.JLabel Mesa;
    private javax.swing.JRadioButton Mixto;
    private javax.swing.JLabel Nombre;
    private javax.swing.JRadioButton Pollo;
    private javax.swing.JRadioButton Ternera;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox conBebida;
    private javax.swing.JCheckBox conPatatas;
    private javax.swing.JCheckBox conSalsa;
    private javax.swing.JCheckBox conVerdura;
    private javax.swing.JButton jButton2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMesa;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JComboBox<String> listaComida;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private javax.swing.JToggleButton verPedidos;
    // End of variables declaration//GEN-END:variables
}
